# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-11-28 14:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('var_choice_text', models.CharField(max_length=200)),
                ('var_votes_int', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('var_question_description', models.CharField(max_length=200)),
                ('var_question_title', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='choices',
            name='var_question_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.Questions'),
        ),
    ]
